"""create rides table

Revision ID: 2517fe72ebd7
Revises: 360e882dac1b
Create Date: 2026-08-03 22:06:08.111299

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2517fe72ebd7'
down_revision: str | None = '360e882dac1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column(
        'status',
        sa.Enum('requested', 'accepted', 'ongoing', 'completed', 'cancelled', name='ride_status'),
        server_default='requested',
        nullable=False,
    ),
    sa.Column('pickup_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pickup_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('dropoff_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('dropoff_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column(
        'requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('rides')
    sa.Enum(name='ride_status').drop(op.get_bind(), checkfirst=True)
