"""add tier and fare columns to rides

Revision ID: 52d2fb859b6b
Revises: a59e3bd98c54
Create Date: 2026-08-24 20:06:43.805573

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52d2fb859b6b"
down_revision: str | None = "a59e3bd98c54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Adjusted from the autogenerated version: ALTER TABLE ... ADD COLUMN with
    # an inline sa.Enum(...) does NOT implicitly CREATE TYPE first (unlike an
    # Enum column declared at CREATE TABLE time) - the type must be created
    # explicitly, or the add_column below fails with "type does not exist".
    ride_tier = sa.Enum("economy", "comfort", "premium", name="ride_tier")
    ride_tier.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rides",
        sa.Column("tier", ride_tier, nullable=False),
    )
    op.add_column("rides", sa.Column("fare", sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rides", "fare")
    op.drop_column("rides", "tier")
    # ### end Alembic commands ###

    # Autogenerate doesn't drop the enum TYPE itself (only the column) -
    # left it in place, a re-upgrade would fail with "type already exists".
    # Mirrors f3b8e21c6a4d's cleanup of user_role for the same reason.
    sa.Enum(name="ride_tier").drop(op.get_bind(), checkfirst=True)
