"""add missing indexes on ride and favorite place foreign keys

Revision ID: 8218e4e07c1e
Revises: 65bf1555a444
Create Date: 2026-08-05 03:39:56.581930

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8218e4e07c1e'
down_revision: str | None = '65bf1555a444'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_favorite_places_user_id', 'favorite_places', ['user_id'], unique=False)
    op.create_index('ix_rides_driver_id', 'rides', ['driver_id'], unique=False)
    op.create_index('ix_rides_rider_id_status', 'rides', ['rider_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rides_rider_id_status', table_name='rides')
    op.drop_index('ix_rides_driver_id', table_name='rides')
    op.drop_index('ix_favorite_places_user_id', table_name='favorite_places')
    # ### end Alembic commands ###
