"""add driver vehicle fields and ratings table

Revision ID: a59e3bd98c54
Revises: f3b8e21c6a4d
Create Date: 2026-08-23 08:36:44.970613

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a59e3bd98c54"
down_revision: str | None = "f3b8e21c6a4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ratings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ride_id", sa.UUID(), nullable=False),
        sa.Column("rider_id", sa.UUID(), nullable=False),
        sa.Column("driver_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score >= 1 AND score <= 5", name="ck_ratings_score_range"),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ride_id"],
            ["rides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rider_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ride_id", name="uq_ratings_ride_id"),
    )
    op.create_index("ix_ratings_driver_id", "ratings", ["driver_id"], unique=False)
    op.add_column("driver_profiles", sa.Column("vehicle_type", sa.String(length=50), nullable=True))
    op.add_column(
        "driver_profiles", sa.Column("vehicle_color", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "driver_profiles", sa.Column("license_plate", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("driver_profiles", "license_plate")
    op.drop_column("driver_profiles", "vehicle_color")
    op.drop_column("driver_profiles", "vehicle_type")
    op.drop_index("ix_ratings_driver_id", table_name="ratings")
    op.drop_table("ratings")
    # ### end Alembic commands ###
